##=================== PATH ============================##
root_path: /openstack-files
##=================== REPOSITORY ======================##
##############
## reposync
##############
reposync_path: "{{ root_path }}/repository"

##############
## add-common-repo
##############
packages:
  - centos-release-openstack-bobcat
  - centos-release-ceph-reef
  - cephadm
  - yum-utils
  - epel-release
  - ceph-common

##############
## add-cephadm-repo
##############
ceph_version: reef

##############
## create-local-repofile
##############
localrepo_baseurl: http://repository
localrepo_filename: local
localrepo_file: "{{ reposync_path }}"

##====================== REGISTRY =====================##
##############
## find_images_with_tag 
##############
kolla_registry_prefix: "docker.io/kolla"
kolla_tag_version: "2023.2-rocky-9"
kolla_services:
  - aodh
  - barbican
  - blazar
  - ceilometer
  - ceph_rgw
  - cinder
  - cloudkitty
  - collectd
  - cyborg
  - designate
  - etcd
  - glance
  - gnocchi
  - grafana
  - hacluster
  - heat
  - horizon
  - influxdb
  - ironic
  - iscsid
  - keystone
  - kuryr
  - letsencrypt
  - loadbalancer
  - magnum
  - manila
  - mariadb
  - masakari
  - memcached
  - mistral
  - multipathd
  - neutron
  - nova
  - octavia
  - opensearch
  - opensearch_dashboards
  - openvswitch_enable_ovs_dpdk
  - ovn
  - placement
  - prometheus
  - rabbitmq
  - redis
  - skyline
  - swift
  - tacker
  - telegraf
  - trove
  - venus
  - watcher
  - zun

##############
# service-images-pull
# ############
etc_images:
  - nginx:1.25.5
  - registry:2.8.3
  - quay.io/ceph/ceph:v18
  - quay.io/ceph/ceph-grafana:9.4.7
  - quay.io/prometheus/prometheus:v2.43.0
  - quay.io/prometheus/alertmanager:v0.25.0
  - quay.io/prometheus/node-exporter:v1.5.0
    
##############
## images-save
##############
registry_image_path: "{{ root_path }}/registry"

##================= KOLLA-ANSIBLE INSTALL ==================##
# 현재 디렉토리의 전체 경로를 가져옵니다.
current_directory: "{{ lookup('pipe', 'pwd') }}"
local_root_path:  "/{{ current_directory.split('/') | select('match', '[^ ]') | first }}"
venv_path: "{{ local_root_path }}/venv"
copy_kolla_config: "{{ venv_path }}/share/kolla-ansible/etc_examples/kolla"
dest_root: "{{ local_root_path }}/git"
gits:
  - git_repo: "https://opendev.org/openstack/kolla.git"
    git_clone_dest: "{{ dest_root }}/kolla"
    version: "stable/2023.2"
    git_filename: "file:///{{ dest_root }}/kolla"

  - git_repo: "https://opendev.org/openstack/kolla-ansible.git"
    git_clone_dest: "{{ dest_root }}/kolla-ansible"
    version: "stable/2023.2"
    git_filename: "file:///{{ dest_root }}/kolla-ansible"

##================  NGINX SERVER (REPOSITORY) =============##
nginx_conf_copy_path: "{{ localrepo_file }}"
nginx_port: "80:80"
nginx_hostname: "root"

##================  REGISTRY SERVER =======================##
private_registry_hosts: "myregistry"
private_registry_ip: "10.130.39.41"
private_registry_url: "myregistry:5000"
private_registry_username: admin
private_registry_password: admin
private_registry_server_auth: "{{ registry_image_path }}/auth"
