##########################################################
# PATH CONFIGURATION
##########################################################
# `DOWNLOAD` ROOT PATH
root_path: /openstack-files

# `SAVE IMAGE` ROOT PATH
registry_image_save_path: "{{ root_path }}/registry"

# `REPOSYNC` ROOT PATH
repository_file_save_path: "{{ root_path }}/repository"

####################################################################
# REPOSITORY CONFIG 
####################################################################
nginx_container_config:
  container_image_path: "{{ registry_image_save_path }}"
  port: "80:80"
  hostname: "root"
  conf_path: /etc/nginx.conf
  mount_volume: "{{ repository_file_save_path }}"
  container_volume: /repository

###################################################################
# REGISTRY CONFIG
# #################################################################
registry_image_path: "{{ registry_image_save_path }}"

##================== HOST ===============================##
controllers:
  - ip: 10.130.39.26
    hostname: controller1

  - ip: 10.130.39.27
    hostname: controller2

cephs:
  - ip: 10.130.39.21
    hostname: ceph-1
    labels: mgr,mon,osd

  - ip: 10.130.39.22
    hostname: ceph-2
    labels: mon,mds,nfs,osd

  - ip: 10.130.39.23
    hostname: ceph-3
    labels: mon,rgw,osd

computes:
  - ip: 10.130.39.24
    hostname: compute1

  - ip: 10.130.39.25
    hostname: compute2

repository:
  - ip: 10.130.39.41
    hostname: repository myregistry time.local.net


##================= KOLLA-ANSIBLE INSTALL ==================##
# 현재 디렉토리의 전체 경로를 가져옵니다.
current_directory: "{{ lookup('pipe', 'pwd') }}"
local_root_path:  "/{{ current_directory.split('/') | select('match', '[^ ]') | first }}"
venv_path: "{{ local_root_path }}/venv"
copy_kolla_config: "{{ venv_path }}/share/kolla-ansible/etc_examples/kolla"
copy_inventory_path: "{{ venv_path }}/share/kolla-ansible/ansible/inventory/multinode"
dest_root: "{{ local_root_path }}/git"
gits:
  - git_repo: "https://opendev.org/openstack/kolla.git"
    git_clone_dest: "{{ dest_root }}/kolla"
    version: "stable/2023.2"
    git_filename: "file:///{{ dest_root }}/kolla"

  - git_repo: "https://opendev.org/openstack/kolla-ansible.git"
    git_clone_dest: "{{ dest_root }}/kolla-ansible"
    version: "stable/2023.2"
    git_filename: "file:///{{ dest_root }}/kolla-ansible"


##================  REGISTRY SERVER =======================##
private_registry_hosts: "myregistry"
private_registry_ip: "{{ groups['repository'][0]['ansible_default_ipv4']['address'] }}"
private_registry_url: "myregistry:5000"
private_registry_username: admin
private_registry_password: admin
private_registry_server_auth: "{{ registry_image_path }}/auth"
private_registry_insecure: "true"

##=============== NEXUS3 SERVER ===========================##
nexus_port: "8081:8081" # 80:80
nexus_hostname: "root"
nexus_data_path: "{{ root_path }}/nexus-data"
nexus_sonatype_work: "{{ root_path }}/sonatype-work"

#/etc/pip.conf 생성 
nexus_domain: "repository"
nexus_pip_url: "http://{{ nexus_domain }}"
nexus_pip_port: "8081"
nexus_pip_reponame: "python-pip"
nexus_pip_trusted_host: "{{ nexus_domain }}"

##=============== CEPH_INSTALL ============================##
ceph:
  bootstrap:
    registry: 
      url: "myregistry:5000"
      username: "admin"
      password: "admin"
      image: "myregistry:5000/ceph/ceph:v18"
    mon_ip: "10.130.39.21"
    initial_conf:
      images:
        - mgr/cephadm/container_image_prometheus = {{ private_registry_url }}:5000/prometheus
        - mgr/cephadm/container_image_node_exporter = {{ private_registry_url }}:5000/node_exporter
        - mgr/cephadm/container_image_grafana = {{ private_registry_url }}:5000/grafana
        - mgr/cephadm/container_image_alertmanager = {{ private_registry_url }}:5000/alertmanger
  hosts:
    labels:
      - name: ceph-1
        label: mgr,mon,osd 
      - name: ceph-2
        label: mon,mds,nfs,osd
      - name: ceph-3
        label: mon,rgw,osd
    add:
      - ceph-2
      - ceph-3

ceph_image: ceph/ceph:v18
grafana: ceph/ceph-grafana:9.4.7
prometheus: prometheus/prometheus:v2.43.0
alertmanager: prometheus/alertmanager:v0.25.0
node_exporter: prometheus/node-exporter:v1.5.0

custom_images:
  - "ceph config set mgr mgr/cephadm/container_image_prometheus {{ private_registry_url }}/{{ prometheus }}"
  - "ceph config set mgr mgr/cephadm/container_image_grafana {{ private_registry_url }}/{{ grafana }}"
  - "ceph config set mgr mgr/cephadm/container_image_alertmanager {{ private_registry_url }}/{{ alertmanager }}"
  - "ceph config set mgr mgr/cephadm/container_image_node_exporter {{ private_registry_url }}/{{ node_exporter }}"


# ceph-orch-label
ceph_node:
  - name: "{{ groups['ceph'][0] }}"
    labels: mgr,mon,osd
  - name: "{{ groups['ceph'][1] }}"
    labels: mon,mds,nfs,osd
  - name: "{{ groups['ceph'][2] }}"
    labels: mon,rgw,osd

