- name: PULL & SAVE ALL IMAGE of KOLLA
  hosts: download
  tasks:
      
    # (NGINX, REGISTRY, CEPH..)
    - name: Apply Role service-image-pull
      include_role:
        name: service-images-pull
      vars:
        pull_images: "{{ etc_images }}"

    - name: podman images 명령을 통해서 리스트 생성
      ansible.builtin.include_role:
        name: podman-images
      vars:
        tag_version: ""
        podman_images_result: "{{ podman_images }}"

    - name:
      debug:
        var: podman_images_result

    - name: Pull-Kolla-Image
      include_role:
        name:  pull-all-kolla-image
      ignore_errors: true

    - name:
      ansible.builtin.include_role:
        name: ensure_dir
      vars:
        path: "{{ registry_image_path }}"

    - ansible.builtin.include_role:
        name: images-save
      vars:
        save_list: "{{ podman_images }}" 
