- name: Image Pull & Save
  hosts: registry
  tasks:
    # pull from group_vars/registry.yml
    - name: 콜라이미지를 제외한 이미지 Pull
      ansible.builtin.include_role:
        name: image-pull
      register: image_pull_result

    - name: image_pull_result
      debug:
        var: image_pull_result

    - name: 특정 ORG 대상으로 모든 레포지토리 검색 후, 특정 태그로 다시 검색하여 리스트 추출
      ansible.builtin.import_role:
        name: get-registry-list-from-org
      vars:
        registry_url: "docker.io"
        namespace: "kolla"
        registry_api_url: "https://hub.docker.com/v2/repositories"
        request_url: "{{ registry_api_url }}/{{ namespace }}"
        specific_tag: "2023.2-rocky-9"

    - name: imageList Lookup
      set_fact:
        image_list: "{{ lookup('file', 'roles/get-registry-list-from-org/files/include_tag.list').splitlines() }}"

    - name: pull images
      ansible.builtin.include_role:
        name: image-pull
      vars:
        images: "{{ image_list }}"

    - name: debug
      debug: 
        msg: kolla_image_pull_result
      
