---
#- name: /etc/hosts create
#  hosts: all
#  become: true
#  roles:
#    - create-hostsfile 

- name: copy yum.repos.d file
  hosts: localhost 
  become: true
  serial: 1
  roles:
    - copy-repofiles

#- name: copy chrony
#  hosts: chrony-client
#  become: true
#  roles:
#    - copy-chrony-conf

- name: create /etc/containers/registries.conf
  hosts: internal
  become: true
  roles:
    - create-registries-conf
  
  
- name: copy podman-auth
  hosts: internal
  become: true
  roles:
    - create-podman-auth-json
