---
- name: CREATE REPOSITORY SERVER
  hosts: repository
  become: true
  tasks:
    - name: create_repository
      include_role:
        name: create-repository
      vars:
        repository_file_path: "{{ localrepo_file }}"
    

