---
- name: CREATE REPOSITORY SERVER
  hosts: repository
  become: true
  vars_files:
    - group_vars/repository.yml
  tasks:
    - name: create_repository
      include_role:
        name: create-repository
         

