
# required ansible.cfg options's "host_key_check=false"
- name: 키 확인
  hosts: "{{ groups['ceph'] | first }}"
  vars:
    hosts: "{{ ceph.hosts }}"
  become: yes
  tasks:
    - name: copy cephadm pub-key to except admin-node
      ansible.builtin.shell: |
        ceph cephadm get-pub-key > /root/ceph.pub
      run_once: true

    - name: Copy cephadm pub-key to Ansible control node
      fetch:
        src: /root/ceph.pub
        dest: /tmp/
        flat: yes
      run_once: true

- name: 키 복사
  hosts: ceph
  gather_facts: false
  tasks:
    - name: Copy cephadm pub-key to hosts
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/tmp/ceph.pub') }}"
      when: inventory_hostname != groups['ceph'] | first
