
# required ansible.cfg options's "host_key_check=false"
- name: cephadd-host
  hosts: "{{ groups['ceph'] | first }}"
  vars:
    hosts: "{{ ceph.hosts }}"
  become: yes
  tasks:
    - name: copy cephadm pub-key to except admin-node
      ansible.builtin.command: |
        ceph cephadm get-pub-key > ~/ceph.pub;
        ssh-copy-id -f -i ~/ceph.pub root@{{ item }}
      loop: "{{ hosts.add }}"
