---
- name: Registry
  hosts: download
  become: true
  vars:
    debug_mode: true
  tasks:
    - name: Print value etc_images
      debug:
        msg: | 
          groupvars/all.yml
          etc_images 의 값:  {{ etc_images }}
      when: debug_mode

    # (NGINX, REGISTRY, CEPH..)
    - name: Apply Role service-image-pull    
      include_role:
        name: service-images-pull
      vars:
        pull_images: "{{ etc_images }}"

    - name: Print service-images-pull result
      debug:
        var: save_images_result.results | map(attribute='image') | flatten | map(attribute='Names') | flatten 
      when: debug_mode

    # 이미지를 검색 후, 특정 태그가 포함되었는지 체크하여 반환
    - name: Apply Role find-images-with-tag
      ansible.builtin.include_role:
        name: find-images-with-tag
      vars:
        registry_prefix: "{{ kolla_registry_prefix }}" 
        tag_version: "{{ kolla_tag_version }}"
        services: "{{ kolla_services }}" 

    - name: KOLLA-IMAGE LIST
      debug:
        var: image_list

    - name: Apply Role service-image-pull (KOLLA)
      ansible.builtin.include_role:
        name: service-images-pull
      vars:
        pull_images: "{{ image_list }}"

    - name: podman images 명령을 통해서 리스트 생성
      ansible.builtin.include_role:
        name: podman-images
      vars:
        tag_version: ""
        podman_images_result: "{{ podman_images }}"
    
    - name:
      debug:
        var: podman_images_result

    - name:  
      ansible.builtin.include_role:
        name: ensure_dir
      vars:
        path: "{{ registry_image_path }}"

    - ansible.builtin.include_role:
        name: images-save
      vars:
        save_list: "{{ podman_images }}"

