---
# tasks file for roles/create-chrony-server
- name: Chrony 패키지 설치
  ansible.builtin.package:
    name: chrony
    state: present

- name: 생성 chrony.conf & 복사 /etc/chrony.conf
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify: Restart chronyd

- name: 방화벽 123/udp 오픈
  ansible.posix.firewalld:
    port: 123/udp
    permanent: true
    state: enabled

