---
# tasks file for add-repo
- name: remove_repo
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ packages }}"
  register: remove_repo_result

- name: debug
  debug:
    var: remove_repo_result

- name: add-repo
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  register: add_repo_result

- name: debug
  debug:
    var: add_repo_result

