---
# tasks file for roles/create-podman-auth-json
- name: Ensure Dir
  file:
    path: ~/.config/containers
    state: directory
    mode: '0755'

- name: Create Auth
  shell: "echo -n {{ private_registry_username }}:{{ private_registry_password }} | base64"
  register: auth

- name: Debug
  debug:
    var: auth.stdout

- name: create template
  template:
    src: auth.json.j2
    dest: ~/.config/containers/auth.json
