---
- name: debug
  debug:
    var: tag_version

- name: generate query string
  set_fact:
    query: "[].images[?contains(Tags, '{{ tag_version }}')].Name"

- name: debug
  debug:
    var: query

- name: tag
  set_fact:
    image_list: "{{ search_with_tags.results | json_query(query | string ) | flatten | map('regex_replace', '(.+)', '\\1:' ~ tag_version ) | flatten | list }}"
 

      
