---
- name: 서비스 이름으로 이미지검색
  import_tasks: podman_search.yml

- name: 검색된 이미지리스트 추출
  import_tasks: extract_image_list.yml

- name: 추출된 이미지리스트에서 찾
  import_tasks: related_tag_with_searched_images.yml

- name: 태그중에 특정태그가 포함되어 있는지 체크 후, image 목록을 다시 반환
  import_tasks: filter_specific_tag.yml
