---
- name: Login Private Registry
  containers.podman.podman_login:
    username: "{{ private_registry_username }}"
    password: "{{ private_registry_password }}"
    registry: "{{ private_registry_url }}"
    tlsverify: false

- name: Get list of Podman images
  command: podman images --format "{{ '{{.Repository}}:{{.Tag}}' }}"
  register: podman_images

- name: Tag docker.io and quay.io images to myregistry:5000
  containers.podman.podman_tag:
    image: "{{ item }}"
    target_names: "{{ private_registry_url }}/{{ item | regex_replace('^docker.io/', '') | regex_replace('^quay.io/', '') }}"
  with_items:
    - "{{ podman_images.stdout_lines | select('match', '^docker.io') | list }}"
    - "{{ podman_images.stdout_lines | select('match', '^quay.io') | list }}"


- name: Push images to myregistry:5000
  shell: podman push {{ item }}
  with_items:
    - "{{ podman_images.stdout_lines | select('match', private_registry_url ) | list }}"
