---
- name: List Podman images
  shell: "podman images -n --format '{% raw %}{{.Repository}}:{{.Tag}}{% endraw %}'"
    #shell: "podman images -n --format '{% raw %}{{.Repository}}:{{.Tag}}{% endraw %}' --filter 'reference=*:{{ tag_version }}'"
  register: podman_images

