- name: nginx run
  containers.podman.podman_container:
    name: nginx
    image: "docker.io/nginx"
    state: started
    recreate: true
    ports:
      - "{{ nginx_container_config.port }}" # 80:80
    hostname: "{{ nginx_container_config.hostname }}"
    volumes:
      - "{{ nginx_container_config.mount_volume }}:{{ nginx_container_config.container_volume }}:ro" # repository 경로 마운트
      - "{{ nginx_container_config.conf_path }}:/etc/nginx/nginx.conf" # nginx conf 경로 마운트
    restart_policy: unless-stopped
    interactive: false # option -i
    tty: false # option -t

- name: SELINUX Config
  ansible.builtin.shell:
    cmd: "chcon -R -t httpd_sys_content_t {{ nginx_container_config.mount_volume }}"

- name: SELINUX Permissive
  selinux:
    policy: targeted
    state: permissive

- name: Ensure SELinux config
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'
    state: present
