---
# tasks file for roles/create_repository
- name: find image files (.tar file)
  find:
    paths: "{{ registry_image_path }}/"
    patterns: "*nexus3*.tar"
    recurse: yes
  register: image_files

- debug:
    msg: "{{ image_files }}"

- name: image load
  containers.podman.podman_load:
    input: "{{ item }}"
  loop: "{{ image_files.files | map(attribute='path') | list }}"
