---
# tasks file for roles/images-save
- name: save_image_name
  set_fact:
    image_name: "{{ item }}"

- name: Check if image tar file exists
  ansible.builtin.stat:
    path: "{{ registry_image_path }}/{{ item | replace('/', '_') | replace(':', '_') }}.tar"
  register: image_file_stat

- name: images-save
  containers.podman.podman_save:
    image: "{{ item }}"
    dest: "{{ registry_image_path }}/{{ item | replace('/', '_') | replace(':', '_') }}.tar"
  when: not image_file_stat.stat.exists
  register: image_save_result

- name: debug
  debug:
    msg: "{{ image_name }}"  
