---
# tasks file for install-ceph

- name: Chrony Setting
  ansible.builtin.include_tasks: chrony.yml

- name: Cephadm install
  ansible.builtin.include_tasks: cephadm_install.yml
    
- name: ssh-keygen
  ansible.builtin.include_tasks: ssh-keygen.yml

- name: ssh-keygen
  ansible.builtin.include_tasks: cephadm_bootstrap.yml
